version: '3'

services:

  database:
    #container_name: database
    #image: mysql:8.0
    #command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: nuvola
      MYSQL_USER: nuvola
      MYSQL_PASSWORD: nuvola
    # ports:
    #   - '4306:3306'
    # volumes:
    #   - ./mysql:/var/lib/mysql

  app:
    #container_name: app
    build:
      context: .
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - database